import = ["/Users/kevinanielsen/.config/alacritty/themes/catpuccin-mocha.toml"]

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 8
y = 2

[keyboard]
bindings = [
  { key = "Left",     mods = "Alt",     chars = "\u001bb"                       }, # Skip word left
  { key = "Right",    mods = "Alt",     chars = "\u001bf"                       }, # Skip word right
  { key = "Left",     mods = "Command", chars = "\u001bOH",   mode = "AppCursor"   }, # Home
  { key = "Right",    mods = "Command", chars = "\u001bOF",   mode = "AppCursor"   }, # End
  { key = "Back",     mods = "Command", chars = "\u00115"                        }, # Delete line
  { key = "Back",     mods = "Alt",     chars = "\u0011b\u007f"                    }, # Delete word
]

[shell]
program = "/bin/zsh/"
