import = ["/Users/kevinanielsen/.config/alacritty/themes/catpuccin-mocha.toml"]

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[window]
decorations = "none"

[window.padding]
x = 8
y = 2

[keyboard]
bindings = [
  { key = "Back", mods = "Command", chars = "\u0015" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" }
]
