add_newline = false

command_timeout = 10000

format = """$directory$character"""
right_format = """$all"""

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '  '

[golang]
format = '[ $version](bold cyan) '

[kubernetes]
symbol = '󱃾 '
disabled = false
detect_files = ['k8s', 'Dockerfile']
detect_extensions = ['yaml']
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]
'arn:aws:eks:us-west-2:577926974532:cluster/gal-kub-demo-cluster' = 'gal'
