import = [
  "~/.config/alacritty/themes/rose-pine.toml"
]

[env]
 TERM = "xterm-256color"

[font]
size = 16
normal.family = "JetBrainsMono Nerd Font"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

[keyboard]
bindings = [
  { key = "Back", mods = "Command", chars = "\u0015" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" }
]
